[package]
name = "straccoon"
version = "0.0.1"
authors = ["Nicolas Kirchner <nicolas.kirchner@gmail.com"]
license = "Apache-2.0/MIT"
edition = "2018"

[dependencies]
ascii = "1.0"
slice-deque = "0.3"
slice-of-array = "0.2"
owning_ref = { git = "https://github.com/Kimundi/owning-ref-rs" }
